/* config.h. Generated by cmake from config.h.cmake */

/* Defined if your compiler supports some byte swap functions */
#define   HAVE_MSC_BYTESWAP 1

/* Defined if your compiler supports some atomic operations */
#define   HAVE_STD_ATOMIC 1
//#define   HAVE_WIN_ATOMIC 1

/* Defined if your compiler supports some safer version of vsprintf */
#define   HAVE_VSPRINTF_S 1

/* Defined if your compiler supports ISO _strdup */
#define   HAVE_ISO_STRDUP 1